[package]
name = "xdv_lib"
version = "0.1.0"
authors = ["XDV Contributors <dev@xdv.local>"]
edition = "2026"
description = "XDV target runtime library for boot/runtime services"
license = "DOSL"

[workspace]
members = [
    "sector/xdv_lib"
]
